export const browserCoreExamples = [
  "edwinpai browser status",
  "edwinpai browser start",
  "edwinpai browser stop",
  "edwinpai browser tabs",
  "edwinpai browser open https://example.com",
  "edwinpai browser focus abcd1234",
  "edwinpai browser close abcd1234",
  "edwinpai browser screenshot",
  "edwinpai browser screenshot --full-page",
  "edwinpai browser screenshot --ref 12",
  "edwinpai browser snapshot",
  "edwinpai browser snapshot --format aria --limit 200",
  "edwinpai browser snapshot --efficient",
  "edwinpai browser snapshot --labels",
];

export const browserActionExamples = [
  "edwinpai browser navigate https://example.com",
  "edwinpai browser resize 1280 720",
  "edwinpai browser click 12 --double",
  'edwinpai browser type 23 "hello" --submit',
  "edwinpai browser press Enter",
  "edwinpai browser hover 44",
  "edwinpai browser drag 10 11",
  "edwinpai browser select 9 OptionA OptionB",
  "edwinpai browser upload /tmp/file.pdf",
  'edwinpai browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "edwinpai browser dialog --accept",
  'edwinpai browser wait --text "Done"',
  "edwinpai browser evaluate --fn '(el) => el.textContent' --ref 7",
  "edwinpai browser console --level error",
  "edwinpai browser pdf",
];
