#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${EDWINPAI_INSTALL_E2E_IMAGE:-${OPENCLAW_INSTALL_E2E_IMAGE:-${CLAWDBOT_INSTALL_E2E_IMAGE:-edwinpai-install-e2e:local}}}"
INSTALL_URL="${EDWINPAI_INSTALL_URL:-${OPENCLAW_INSTALL_URL:-${CLAWDBOT_INSTALL_URL:-https://edwinpai.com/install.sh}}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
EDWINPAI_E2E_MODELS="${EDWINPAI_E2E_MODELS:-${OPENCLAW_E2E_MODELS:-${CLAWDBOT_E2E_MODELS:-}}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e EDWINPAI_INSTALL_URL="$INSTALL_URL" \
  -e EDWINPAI_INSTALL_TAG="${EDWINPAI_INSTALL_TAG:-${OPENCLAW_INSTALL_TAG:-${CLAWDBOT_INSTALL_TAG:-latest}}}" \
  -e EDWINPAI_E2E_MODELS="$EDWINPAI_E2E_MODELS" \
  -e EDWINPAI_INSTALL_E2E_PREVIOUS="${EDWINPAI_INSTALL_E2E_PREVIOUS:-${OPENCLAW_INSTALL_E2E_PREVIOUS:-${CLAWDBOT_INSTALL_E2E_PREVIOUS:-}}}" \
  -e EDWINPAI_INSTALL_E2E_SKIP_PREVIOUS="${EDWINPAI_INSTALL_E2E_SKIP_PREVIOUS:-${OPENCLAW_INSTALL_E2E_SKIP_PREVIOUS:-${CLAWDBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
